### ISSUE TITLE
ERROR::CTag::__init__::Given souptag is not a bs4.element.Tag instance. when building.

### ISSUE THREAD

**Issue by jdbaptist** [SpiceBucks/SpicyArbs#1]
The builds on the master branch fail.  

Logs:
$ python main_webscraper.py -j9

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html

DEBUG::Examining American Football arbitrage opportunities.
DEBUG::Examining arbitrage opportunities in game: Kansas City Chiefs at Tampa Bay Buccaneers.
DEBUG::Considering market: Longest Touchdown Yardage.
DEBUG::Considering market: Lead at the End of Every Quarter.
ERROR::CTag::__init__::Given souptag is not a bs4.element.Tag instance.
ERROR::Exiting program with failure status.

**Comment by SpiceBucks** [comment]
Fixed now
